const mainnet = ":unicorn: #**Ethereum** :unicorn:\nEthereum was founded by boy genius Vitalik Buterin and is the metaverse hub of entertainment, finance, and engineering. Traffic and pollution is a major problem so expect journeys to be expensive and slow, sometimes taking mules a few minutes or more on busy days. Ethereum’s top engineers are parallelising it into a multiverse but for now its creaking serial tx superhighway will have to do.\n\n:dollar: Currencies  - ETH, DAI, ENJ, ERC20/1155s\n:gem: Payments    - ETH\n:package: Item Types - ERC721/1155s\n:rocket: Speed          - Slow\n:moneybag: Costs          - High\n\n**Exchange:**\n<https://uniswap.io/>\n**Marketplace:**\n<https://opensea.io/>\n**Buy Currency:**\n<https://instant.ramp.network/>\n<https://www.coinbase.com/>\n**Stash Wallet:**\n<https://metamask.io/>\n----------\n*List metaverses:* `!mule metaverse list`"
const rinkeby = ":test_tube: :unicorn: #**Rinkeby** :test_tube: :unicorn:\nRinkeby is one of Ethereum’s laboratories used for experimentation. Anything created or owned here is liable to spontaneously combust, mutate, or never to have existed. **Nothing here is real**.\n\n:warning: **Warning: Volatile area. Balances and inventory may be lost at any time!**\n:dollar: Currencies  - RETH, ERC20/1155s\n:gem: Payments    - RETH\n:package: Item Types - ERC721/1155s\n:rocket: Speed          - Medium\n:moneybag: Costs          - Medium\n\n**Free RETH:**\n<https://faucet.rinkeby.io/>\n----------\n*List metaverses:* `!mule metaverse list`"
const kovan = ":test_tube: :unicorn: #**Kovan** :test_tube: :unicorn:\nKovan is one of Ethereum’s laboratories used for experimentation. Anything created or owned here is liable to spontaneously combust, mutate, or never to have existed. **Nothing here is real**.\n\n:warning: **Warning: Volatile area. Balances and inventory may be lost at any time!**\n:dollar: Currencies  - KETH, ERC20/1155s\n:gem: Payments    - KETH\n:package: Item Types - ERC721/1155s\n:rocket: Speed          - Medium\n:moneybag: Costs          - Medium\n\n**Free KETH, KENJ:**\n<https://kovan.faucet.enjin.io/>\n----------\n*List metaverses:* `!mule metaverse list`"
const matic = ":rocket: #**Matic** :rocket:\nMatic is one of Ethereum’s secret laboratories used for side chain experimentation. Anything created or owned here is liable to spontaneously combust, mutate, or never to have existed. **Nothing here is real**.\n\n:warning: **Warning: Volatile area. Balances and inventory may be lost at any time!**\n:dollar: Currencies  - ETH, ERC20/1155s\n:gem: Payments    - ETH\n:package: Item Types - ERC721/1155s\n:rocket: Speed          - Fast\n:moneybag: Costs          - Low\n\n*List metaverses:* `!mule metaverse list`";
const maticMumbai = ":rocket: :test_tube: #**Matic Mumbai** :rocket: :test_tube:\nMatic is one of Ethereum’s secret laboratories used for side chain experimentation. Anything created or owned here is liable to spontaneously combust, mutate, or never to have existed. **Nothing here is real**.\n\n:warning: **Warning: Volatile area. Balances and inventory may be lost at any time!**\n:dollar: Currencies  - ETH, ERC20/1155s\n:gem: Payments    - ETH\n:package: Item Types - ERC721/1155s\n:rocket: Speed          - Fast\n:moneybag: Costs          - Low\n\n**Free Matic Mumbai ETH:**\n<https://faucet.matic.network/>\n----------\n*List metaverses:* `!mule metaverse list`";

/** Network description config */
module.exports = {
  mainnet,
  rinkeby,
  kovan,
  matic,
  "matic-mumbai": maticMumbai,
}
