const crypto    = require('crypto');
const validator = require('validator');
const bcrypt    = require('bcrypt');

/* SAME AS RECOVERY */
/**
 * @module /change-password
 * @category API
 * @subcategory Client
 */
/**
 * /change-password
 * @param {Object} req.body.keystore - keytore file generated by client
 * @param {string} req.body.password_hash - old password hash
 * @param {string} req.body.new_password_hash - new password hash
 * @param {string} req.body.new_password_check - confirm new password
 */
module.exports = async(req,res) => {
  let resp = res.locals.resp;
  let mule = res.locals.mule;
  if (!req.body || !req.body.keystore || !req.body.password_hash || !req.body.new_password_hash || !req.body.new_password_check || req.body.new_password_check != req.body.new_password_hash) {
    return resp(req,res,400,{'error': 'Invalid request.'},{});
  }
  if (!req.session || !req.session.user) {
    return resp(req,res,401,{'error': 'User is not logged in.'},{});
  }

  /* Confirm User */
  if (!validator.isHash(req.body.password_hash, 'sha256')) {
    return resp(req,res,400,{'error':'Invalid username/password combination.'},{});
  }
  let password_hash = req.body.password_hash;

  let account = await mule.sql.query('web', 'getAccount', [req.session.user]);
  if (!account || account.rowCount < 1) {
    return resp(req,res,500,{'error':'Internal error'},{});
  }
  let name = account.rows[0]['mule_name'];
  let passHash = await mule.sql.query('web', 'getPasswordHash', [name]);
  if (!passHash || passHash.rowCount < 1 || !passHash.rows[0]['user_uuid'] || !passHash.rows[0]['password_hash']) {
    return resp(req,res,400,{'error':'Invalid username/password combination.'},{});
  }
  let nameHash = await crypto.createHash('sha256').update(String(name)).digest('hex');
  if (!bcrypt.compareSync(nameHash + req.body.password_hash, passHash.rows[0]['password_hash'])) {
    return resp(req,res,400,{'error':'Invalid username/password combination.'},{});
  }
  if (passHash.rows[0]['user_uuid'] != req.session.user) {
    return resp(req,res,400,{'error': 'Could not verify password.'},{});
  }

  /* Confirm new password hash */
  if (!validator.isHash(req.body.new_password_hash, 'sha256')) {
    return resp(req,res,400,{'error':'Invalid password hash.'},{});
  }
  let hashedPassword = String(bcrypt.hashSync(nameHash + req.body.new_password_hash, 10));
  let new_password_hash = hashedPassword;


  /* Confirm keystore */
  try {
    JSON.parse(JSON.stringify(req.body.keystore));
  } catch(ex) {
    return resp(req,res,400,{'error':'Invalid request'},{});
  }
  let keystore = JSON.stringify(req.body.keystore);

  if (JSON.parse(keystore).address.length !== 40 || !validator.isHexadecimal(JSON.parse(keystore).address)) {
    return resp(req,res,400,{'error':'Invalid request'},{});
  }
  let address = '0x' + JSON.parse(keystore).address;

  let update = await mule.sql.query('web', 'updatePassword', [req.session.user, keystore, address, hashedPassword]);
  if (!update || update.rowCount < 1) {
    return resp(req,res,500,{'error':'Internal Error.'},{});
  }

  return resp(req,res,200,{}, {});
}
